// Single source of truth for branches, semesters, courses, note types, and exam types.
// Structured for KLE Dr. M.S. Sheshgiri College of Engineering & BCA/MCA programs.

// ===================== NOTE TYPES =====================
export const NOTE_TYPES = [
  "Textbook",
  "Question Paper",
  "Handwritten Notes",
  "PPT",
] as const;

export type NoteType = (typeof NOTE_TYPES)[number];

// ===================== EXAM TYPES =====================
export const EXAM_TYPES = ["ISA 1", "ISA 2", "ESA"] as const;

export type ExamType = (typeof EXAM_TYPES)[number];

// ===================== COURSE STRUCTURE =====================
// Each course has a code and name.

interface Course {
  code: string;
  name: string;
}

// Branch → semesters available
export const BRANCH_SEMESTERS: Record<string, string[]> = {
  EEE: ["1", "2", "3", "4", "5", "6", "7", "8"],
  "CS-AI": ["1", "2", "3", "4", "5", "6", "7", "8"],
  MCA: ["1", "2", "3", "4"],
  Mechanical: ["1", "2", "3", "4", "5", "6", "7", "8"],
  BCA: ["1", "2", "3", "4", "5", "6"],
  Biomedical: ["1", "2", "3", "4", "5", "6", "7", "8"],
  Civil: ["1", "2", "3", "4", "5", "6", "7", "8"],
  MBA: ["1", "2", "3", "4"],
  ECE: ["1", "2", "3", "4", "5", "6", "7", "8"],
  Chemical: ["1", "2", "3", "4", "5", "6", "7", "8"],
  CSE: ["1", "2", "3", "4", "5", "6", "7", "8"],
};

export const BRANCH_SEM_COURSES: Record<string, Course[]> = {
  "BCA|1": [
    { code: "", name: "Operating Systems" },
    { code: "", name: "Discrete Mathematical Structures" },
    { code: "", name: "Computer Organization and Architecture" },
    { code: "", name: "Problem Solving using C" },
    { code: "", name: "Python Programming" },
    { code: "", name: "Web Technology" },
    { code: "", name: "Professional Communication" },
    { code: "", name: "Corporate Communication Skills" },
  ],
  "BCA|2": [
    { code: "", name: "Linear Algebra and Graph Theory" },
    { code: "", name: "Database Management Systems" },
    { code: "", name: "Data Structures and Algorithms" },
    { code: "", name: "Software Engineering" },
    { code: "", name: "Data Structures and Algorithms Lab" },
    { code: "", name: "Database Management Systems Lab" },
    { code: "", name: "Problem-Solving and Analytical Skills" },
  ],
  "BCA|3": [
    { code: "", name: "Computer Networks" },
    { code: "", name: "Applied Statistics" },
    { code: "", name: "Object-Oriented Programming using Java" },
    { code: "", name: "Full Stack Web Development" },
    { code: "", name: "Data Mining and Analytics" },
    { code: "", name: "Computer Networks Lab" },
    { code: "", name: "Arithmetical Thinking and Analytical Reasoning" },
  ],
  "BCA|4": [
    { code: "", name: "Programming with C# and .Net" },
    { code: "", name: "Software Testing" },
    { code: "", name: "Professional Aptitude and Logical Reasoning" },
    { code: "", name: "Machine Learning" },
    { code: "", name: "DevOps Lab" },
    { code: "", name: "Minor Project-1" },
    { code: "", name: "Industry Readiness and Leadership Skills" },
  ],
  "BCA|5": [
    { code: "", name: "Cloud Computing" },
    { code: "", name: "Information Security" },
    { code: "", name: "Big Data Analytics" },
    { code: "", name: "Professional Elective-1" },
    { code: "", name: "Professional Elective-2" },
    { code: "", name: "Minor Project-2" },
  ],
  "BCA|6": [
    { code: "", name: "Professional Elective-3" },
    { code: "", name: "Professional Elective-4" },
    { code: "", name: "Capstone Project" },
    { code: "", name: "Industry Training" },
    { code: "", name: "Industry Project" },
  ],
  "MBA|1": [
    { code: "", name: "Organizational Theory & Practice" },
    { code: "", name: "Micro and Macro Business Environment" },
    { code: "", name: "Accounting for Managers" },
    { code: "", name: "Business Research Methods" },
    { code: "", name: "Marketing Management" },
    { code: "", name: "Business Statistics and Probability" },
    { code: "", name: "Business Communication" },
    { code: "", name: "Industry Experience Phase - I" },
  ],
  "MBA|2": [
    { code: "", name: "Business Data Analytics" },
    { code: "", name: "Entrepreneurship Development" },
    { code: "", name: "Financial Management" },
    { code: "", name: "Human Resource Management" },
    { code: "", name: "Operations Management" },
    { code: "", name: "Gen AI for Managers" },
    { code: "", name: "Digital Marketing for Rural Business" },
    { code: "", name: "Managerial Communication and Aptitude" },
    { code: "", name: "Industry Experience Phase – II" },
    { code: "", name: "Business Intelligence and Analytics Phase - I" },
    { code: "", name: "Business Venture Phase – I" },
  ],
  "MBA|3": [
    { code: "", name: "Strategic Management" },
    { code: "", name: "Elective I – IV" },
    { code: "", name: "Summer Internship" },
    { code: "", name: "Climate Change & Sustainability Management" },
    { code: "", name: "Industry Experience Phase – III" },
    { code: "", name: "Business Intelligence and Analytics Phase - II" },
    { code: "", name: "Business Venture Phase – II" },
    { code: "", name: "Research Experience Phase – I" },
    { code: "", name: "Social Entrepreneurship Phase – I" },
  ],
  "MBA|4": [
    { code: "", name: "Legal Aspects of Business" },
    { code: "", name: "Supply Chain Management" },
    { code: "", name: "Corporate Dissertation" },
    { code: "", name: "Elective I – IV" },
    { code: "", name: "Research Experience – Phase - II" },
    { code: "", name: "Social Entrepreneurship – Phase – II" },
  ],
  "MCA|1": [
    { code: "", name: "Data Structures using C" },
    { code: "", name: "Database Management System" },
    { code: "", name: "Computer Networks" },
    { code: "", name: "Mathematical Thinking & Logical Reasoning" },
    { code: "", name: "Web Technology" },
    { code: "", name: "Data Structures Lab" },
    { code: "", name: "DBMS Lab" },
    { code: "", name: "Python Programming" },
    { code: "", name: "Critical Thinking and Problem Solving Skills" },
  ],
  "MCA|2": [
    { code: "", name: "OOPS using Java" },
    { code: "", name: "Data Mining" },
    { code: "", name: "Software Engineering" },
    { code: "", name: "Cloud Computing" },
    { code: "", name: "Design and Analysis of Algorithms" },
    { code: "", name: "Operating Systems" },
    { code: "", name: "Java Programming Lab" },
    { code: "", name: "Mini Project-1" },
    { code: "", name: "Communication and Leadership Skills" },
  ],
  "MCA|3": [
    { code: "", name: "Machine Learning" },
    { code: "", name: "Big Data Analytics" },
    { code: "", name: "Programming using C# with .Net" },
    { code: "", name: "Elective-1" },
    { code: "", name: "Elective-2" },
    { code: "", name: "C# .NET Lab" },
    { code: "", name: "Advanced JAVA Programming Lab" },
    { code: "", name: "Minor Project-2" },
  ],
  "MCA|4": [
    { code: "", name: "Capstone Project Work" },
    { code: "", name: "Professional Certification" },
    { code: "", name: "Elective-3 (MOOC)" },
    { code: "", name: "Elective-4 (MOOC)" },
  ],
  "Civil|1": [
    { code: "", name: "Introduction to Calculus" },
    { code: "", name: "Engineering Chemistry" },
    { code: "", name: "Basic Electrical and Electronics Engineering" },
    { code: "", name: "Basic Mechanical Engineering" },
    { code: "", name: "Professional Communication" },
    { code: "", name: "C programming for problem solving" },
    { code: "", name: "Design Thinking for Social Innovation" },
  ],
  "Civil|2": [
    { code: "", name: "Differential Equations and Applications" },
    { code: "", name: "Engineering Physics" },
    { code: "", name: "Engineering Mechanics" },
    { code: "", name: "Problem Solving with Data Structures" },
    { code: "", name: "Computer Aided Engineering Drawing" },
    { code: "", name: "Engineering Exploration" },
  ],
  "Civil|3": [
    { code: "", name: "Linear Algebra" },
    { code: "", name: "Building Technology and Services" },
    { code: "", name: "Surveying" },
    { code: "", name: "Mechanics of Fluids" },
    { code: "", name: "Mechanics of Materials" },
    { code: "", name: "Survey Practice – I" },
    { code: "", name: "Material Testing Lab" },
    { code: "", name: "Building Engineering Drawing" },
    { code: "", name: "Corporate Communication" },
  ],
  "Civil|4": [
    { code: "", name: "Applied Probability and Statistics" },
    { code: "", name: "Structural Analysis-I" },
    { code: "", name: "Water and Wastewater Engineering" },
    { code: "", name: "Concrete Technology" },
    { code: "", name: "Construction Project Management" },
    { code: "", name: "Hydrology & Irrigation Engineering" },
    { code: "", name: "Problem Solving and Analysis" },
    { code: "", name: "Survey Practice – II" },
    { code: "", name: "Concrete Laboratory" },
    { code: "", name: "Generative AI for Civil Engineering" },
  ],
  "Civil|5": [
    { code: "", name: "Structural Analysis-II" },
    { code: "", name: "Geotechnical Engineering" },
    { code: "", name: "Design of RCC Structures" },
    { code: "", name: "Transportation Engineering" },
    { code: "", name: "Construction Economics & Management" },
    { code: "", name: "Arithmetical Thinking and Analytical Reasoning" },
    { code: "", name: "Highway Engineering Laboratory" },
    { code: "", name: "Environmental Engineering Laboratory" },
    { code: "", name: "Computer Aided Design Lab" },
    {
      code: "",
      name: "Mini Project - Applied Sustainability in Civil Engineering",
    },
  ],
  "Civil|6": [
    { code: "", name: "Design of Steel Structures" },
    { code: "", name: "Estimation and Costing" },
    { code: "", name: "Program Elective -1" },
    { code: "", name: "Professional Aptitude & Logical Reasoning" },
    { code: "", name: "Industry Readiness and Leadership Skills" },
    { code: "", name: "Geotechnical Engineering laboratory" },
    { code: "", name: "Construction Engineering & Management Laboratory" },
    { code: "", name: "Design Studio - Steel and RC Structures" },
    { code: "", name: "Minor Project" },
  ],
  "Civil|7": [
    { code: "", name: "Pre-Stressed Concrete" },
    { code: "", name: "Program Elective -2" },
    { code: "", name: "Program Elective -3" },
    { code: "", name: "Program Elective -4" },
    { code: "", name: "Program Elective -5" },
    { code: "", name: "Construction Management Workshop" },
    { code: "", name: "CIPE / EVS (Audit)" },
    { code: "", name: "Senior Design Project" },
  ],
  "Civil|8": [
    { code: "", name: "Program Elective - 6" },
    { code: "", name: "Open Elective – 1" },
    { code: "", name: "Internship Training" },
    { code: "", name: "Capstone Project / Internship Project" },
  ],
  "Mechanical|1": [
    { code: "", name: "Humanities and Social Sciences" },
    { code: "", name: "Basic Sciences (Physics, Chemistry," },
    { code: "", name: "Mathematics)" },
    { code: "", name: "Engineering Sciences" },
    { code: "", name: "Professional Core Courses + SS" },
    { code: "", name: "Professional Elective Courses" },
    { code: "", name: "Open Electives" },
    { code: "", name: "Mini/ Minor project" },
  ],
  "Mechanical|2": [
    { code: "", name: "Humanities and Social Sciences" },
    { code: "", name: "Basic Sciences (Physics, Chemistry," },
    { code: "", name: "Mathematics)" },
    { code: "", name: "Engineering Sciences" },
    { code: "", name: "Professional Core Courses + SS" },
    { code: "", name: "Professional Elective Courses" },
    { code: "", name: "Open Electives" },
    { code: "", name: "Mini/ Minor project" },
  ],
  "Mechanical|3": [
    { code: "", name: "Statistics and Integral Transforms" },
    { code: "", name: "Mechanics of Materials" },
    { code: "", name: "Manufacturing Processes" },
    { code: "", name: "Engineering Thermodynamics" },
    { code: "", name: "Control Systems" },
    { code: "", name: "Manufacturing Processes Lab" },
    { code: "", name: "Control Systems Lab" },
    { code: "", name: "Machine Drawing Lab" },
    { code: "", name: "Corporate Communication" },
  ],
  "Mechanical|4": [
    { code: "", name: "Numerical Methods and Partial Differential Equations" },
    { code: "", name: "Fundamentals of Machine Design" },
    { code: "", name: "Machines & Mechanisms" },
    { code: "", name: "Engineering Materials" },
    { code: "", name: "Mechatronics" },
    { code: "", name: "Microcontroller & Interfacing" },
    { code: "", name: "Microcontroller & Interfacing Lab" },
    { code: "", name: "Machines & Mechanisms Lab" },
    { code: "", name: "Engineering Materials Lab" },
    { code: "", name: "Problem Solving & Analysis" },
  ],
  "Mechanical|5": [
    { code: "", name: "Design of Machine Elements" },
    { code: "", name: "Finite Element Methods" },
    { code: "", name: "Programming Industrial Automation" },
    { code: "", name: "Systems" },
    { code: "", name: "Program Elective-I" },
    { code: "", name: "CAD Modeling & PLM Lab" },
    { code: "", name: "Automation Lab" },
    { code: "", name: "FEM Lab" },
    { code: "", name: "Mini Project" },
    { code: "", name: "Arithmetical Thinking & Analytical Reasoning" },
  ],
  "Mechanical|6": [
    { code: "", name: "Professional Aptitude & Logical Reasoning" },
    { code: "", name: "Fluid Mechanics & Hydraulic Machines" },
    { code: "", name: "Metrology and Quality Engineering" },
    { code: "", name: "Mechatronics System Design" },
    { code: "", name: "Program Elective - 2" },
    { code: "", name: "Metrology and Quality Engineering Lab" },
    { code: "", name: "Minor Project" },
    { code: "", name: "Industry Readiness & Leadership Skills" },
  ],
  "Mechanical|7": [
    { code: "", name: "IC Engines" },
    { code: "", name: "Thermal Engineering Lab" },
    { code: "", name: "Program Elective — 4" },
    { code: "", name: "Program Elective - 5" },
    { code: "", name: "Senior Design Project" },
    { code: "", name: "CIPE/EVS" },
  ],
  "Mechanical|8": [
    { code: "", name: "Program Elective - 6" },
    { code: "", name: "Open Elective" },
    { code: "", name: "Internship — Training (Optional In place of 1 &2)" },
    { code: "", name: "Capstone Project / Internship – Project" },
  ],
  "ECE|1": [
    { code: "", name: "Multivariable Calculus" },
    { code: "", name: "Engineering Chemistry" },
    { code: "", name: "Problem Solving with Data Structures" },
    { code: "", name: "Engineering Exploration" },
    { code: "", name: "Basic Electronics" },
    { code: "", name: "Basic Mechanical Engineering" },
    { code: "", name: "Professional Communication" },
  ],
  "ECE|2": [
    { code: "", name: "Multivariable Calculus" },
    { code: "", name: "Engineering Chemistry" },
    { code: "", name: "Problem Solving with Data Structures" },
    { code: "", name: "Engineering Exploration" },
    { code: "", name: "Basic Electronics" },
    { code: "", name: "Basic Mechanical Engineering" },
    { code: "", name: "Professional Communication" },
  ],
  "ECE|3": [
    { code: "", name: "Integral Transforms and Statistics" },
    { code: "", name: "Corporate Communication" },
    { code: "", name: "Circuit Analysis" },
    { code: "", name: "Analog Electronic Circuits" },
    { code: "", name: "Digital Circuits" },
    { code: "", name: "Signals & Systems" },
    { code: "", name: "Digital Circuits Lab" },
    { code: "", name: "Analog Electronic Circuits Lab" },
    { code: "", name: "Microcontroller Architecture & Programming" },
    { code: "", name: "C Programming (Diploma)" },
  ],
  "ECE|4": [
    { code: "", name: "Linear Algebra & Partial Differential Equations" },
    { code: "", name: "Problem Solving & Analysis" },
    { code: "", name: "Electromagnetic Fields and Waves" },
    { code: "", name: "Linear Integrated Circuits" },
    { code: "", name: "Control Systems" },
    { code: "", name: "ARM Processor & Applications" },
    { code: "", name: "Digital System Design Using Verilog" },
    { code: "", name: "Data Acquisition and Controls Lab" },
    { code: "", name: "ARM Microcontroller Lab" },
    { code: "", name: "Data Structure Applications Lab" },
    { code: "", name: "Data Structure Using C Lab (Diploma)" },
  ],
  "ECE|5": [
    { code: "", name: "Arithmetical Thinking & Analytical Reasoning" },
    { code: "", name: "CMOS VLSI Circuits" },
    { code: "", name: "Communication System" },
    { code: "", name: "Digital Signal Processing" },
    { code: "", name: "Operating System & Embedded Systems Design" },
    { code: "", name: "Machine Learning" },
    { code: "", name: "RTOS Lab" },
    { code: "", name: "CMOS VLSI Circuits Lab" },
    { code: "", name: "Mini Project" },
  ],
  "ECE|6": [
    { code: "", name: "Professional Aptitude and Logical Reasoning" },
    { code: "", name: "Industry Readiness & Leadership Skills" },
    { code: "", name: "Automotive Electronics" },
    { code: "", name: "Computer Communication Networks I" },
    { code: "", name: "PSE Elective 1" },
    { code: "", name: "Computer Communication Networks I Lab" },
    { code: "", name: "Automotive Electronics Lab" },
    { code: "", name: "Minor Project - I" },
    { code: "", name: "Minor Project - II" },
  ],
  "ECE|7": [
    { code: "", name: "Advanced Communication Networks" },
    { code: "", name: "PSE Elective 2" },
    { code: "", name: "PSE Elective 3" },
    { code: "", name: "PSE Elective 4" },
    { code: "", name: "PSE Elective 5" },
    { code: "", name: "Senior Design Project" },
    { code: "", name: "CIPE" },
  ],
  "ECE|8": [
    { code: "", name: "PSE Elective 6" },
    { code: "", name: "Open Elective 1" },
    { code: "", name: "Internship - Training" },
    { code: "", name: "Internship - Project" },
    { code: "", name: "Project Work" },
  ],
  "CSE|1": [
    { code: "", name: "Single Variable Calculus" },
    { code: "", name: "Engineering Physics" },
    { code: "", name: "Engineering Mechanics" },
    { code: "", name: "C Programming for Problem Solving" },
    { code: "", name: "Basic Electrical Engineering" },
    { code: "", name: "Design Thinking for Social Innovation" },
  ],
  "CSE|2": [
    { code: "", name: "Multivariable Calculus" },
    { code: "", name: "Engineering Chemistry" },
    { code: "", name: "Problem Solving with Data Structures" },
    { code: "", name: "Engineering Exploration" },
    { code: "", name: "Basic Electronics" },
  ],
  "CSE|3": [
    {
      code: "",
      name: "Graph Theory and Linear Algebra/ Graph Theory and Calculus",
    },
    { code: "", name: "Discrete Mathematical Structures" },
    { code: "", name: "Computer Organization and Architecture" },
    { code: "", name: "Data Structures and Algorithms" },
    { code: "", name: "Database Management System" },
    { code: "", name: "Database Applications Lab" },
    { code: "", name: "Corporate Communication" },
  ],
  "CSE|4": [
    { code: "", name: "Applied Statistics with R/ Vectors and Linear Algebra" },
    { code: "", name: "Microcontroller: Programming and Interfacing" },
    { code: "", name: "Object-Oriented Programming" },
    { code: "", name: "Principles of Compiler Design" },
    { code: "", name: "Operating System Principles and Programming" },
    { code: "", name: "Exploratory Data Analysis" },
    { code: "", name: "Object Oriented Programming Lab" },
    { code: "", name: "Problem Solving & Analysis" },
  ],
  "CSE|5": [
    { code: "", name: "Software Engineering" },
    { code: "", name: "Computer Networks-1" },
    { code: "", name: "System Software" },
    { code: "", name: "Machine Learning" },
    { code: "", name: "Web Technologies Lab" },
    { code: "", name: "System Software Lab" },
    { code: "", name: "Mini Project" },
    { code: "", name: "Professional Elective-1" },
    { code: "", name: "Arithmetical Thinking & Analytical Reasoning" },
    { code: "", name: "Statistics and Probability" },
  ],
  "CSE|6": [
    { code: "", name: "Computer Networks-2" },
    { code: "", name: "Cloud Computing" },
    { code: "", name: "Professional Elective-2" },
    { code: "", name: "Professional Elective-3" },
    { code: "", name: "Computer Networks Lab" },
    { code: "", name: "Minor Project-1" },
    { code: "", name: "Minor Project-2" },
    { code: "", name: "Industry Readiness & Leadership Skills (Audit)" },
    { code: "", name: "Professional Aptitude & Logical Reasoning (Audit)" },
  ],
  "CSE|7": [
    { code: "", name: "Big Data & Analytics" },
    { code: "", name: "Information Security" },
    { code: "", name: "Professional Elective-4" },
    { code: "", name: "Professional Elective-5" },
    { code: "", name: "Senior Design Project" },
    { code: "", name: "CIPE" },
    { code: "", name: "Minor Project" },
  ],
  "CSE|8": [
    { code: "", name: "Big Data & Analytics" },
    { code: "", name: "Information Security" },
    { code: "", name: "Professional Elective-4" },
    { code: "", name: "Professional Elective-5" },
    { code: "", name: "Senior Design Project" },
    { code: "", name: "CIPE" },
    { code: "", name: "Minor Project" },
    { code: "", name: "Professional Elective-6" },
    { code: "", name: "Open Elective" },
    { code: "", name: "Capstone Project 20ECSW402 / Industry Project" },
    { code: "", name: "Industry Training" },
  ],
  "CS-AI|1": [
    { code: "18ECSP101", name: "C Programming for Problem Solving" },
    { code: "18EECF101", name: "Basic Electronics" },
    { code: "18EMAB101", name: "Single Variable Calculus" },
    { code: "21EPHP101", name: "Applied Physics Lab" },
    { code: "22ECRP101", name: "Engineering Exploration" },
    { code: "22EMEF101", name: "Basic Mechanical Engineering" },
    { code: "22EPHB101", name: "Engineering Physics" },
  ],
  "CS-AI|2": [
    { code: "15ECVF101", name: "Engineering Mechanics" },
    { code: "15EHSH101", name: "Professional Communication" },
    { code: "18ECSP102", name: "Problem Solving with Data Structures" },
    { code: "18EEEF101", name: "Basic Electrical Engineering" },
    { code: "18EMAB102", name: "Multivariable Calculus" },
    { code: "20EHSP101", name: "Design Thinking for Social Innovation" },
    { code: "23ECHB102", name: "Engineering Chemistry" },
  ],
  "CS-AI|3": [
    { code: "22ECAC204", name: "Database Management System" },
    { code: "22ECAP201", name: "Database Application Lab" },
    { code: "24ECAC201", name: "Discrete Mathematical Structures" },
    { code: "24ECAC202", name: "Computer Organization and Architecture" },
    { code: "24ECAC203", name: "Design and Analysis of Algorithms" },
    { code: "24ECAP202", name: "Algorithms Lab" },
    { code: "24EHSA201", name: "Corporate Communication" },
    { code: "24EMAB208", name: "Linear Algebra" },
  ],
  "CS-AI|4": [
    { code: "22ECAC209", name: "Principles of Compiler Design" },
    { code: "24ECAC206", name: "Microcontroller Programming and Interfacing" },
    { code: "24ECAC207", name: "Object Oriented Programming" },
    { code: "24ECAC208", name: "Operating System Principles and Programming" },
    { code: "24ECAC210", name: "Exploratory Data Analysis" },
    { code: "24ECAP206", name: "Object Oriented Programming Lab" },
    { code: "24EHSA202", name: "Problem Solving and Analysis" },
    { code: "24EMAB209", name: "Probability and Statistics" },
  ],
  "CS-AI|5": [
    { code: "22ECAC301", name: "Software Engineering" },
    { code: "22ECAC303", name: "Machine Learning" },
    { code: "22ECAP302", name: "Computer Networks Lab" },
    { code: "22ECAP303", name: "Machine Learning Lab" },
    { code: "22ECAW301", name: "Mini Project" },
    {
      code: "23EHSA303",
      name: "Arithmetical Thinking and Analytical Reasoning",
    },
    { code: "24ECAC302", name: "Computer Networks" },
    { code: "24ECAC308", name: "Internet of Things" },
    { code: "24ECAE336", name: "Computer Vision" },
    { code: "24ECAP304", name: "Web Technologies Lab" },
  ],
  "CS-AI|6": [
    { code: "24ECAC305", name: "Deep Learning" },
    { code: "24ECAC306", name: "Embedded Intelligent Systems" },
    { code: "24ECAC307", name: "Natural Language Processing and Gen AI" },
    { code: "24ECSE320", name: "Applied Computational Medicine" },
    { code: "24ECAE322", name: "Informatica - Intelligent Data Mgmt. Cloud" },
    { code: "24ECAE317", name: "Cloud Computing" },
    { code: "24ECAE339", name: "Blockchain and Distributed Ledgers" },
    { code: "23ECAE335", name: "DevOps and MLOps" },
    { code: "24ECAW304", name: "Minor Project" },
    { code: "16EHSC301", name: "Professional Aptitude & Logical Reasoning" },
    { code: "23EHSA304", name: "Industry Readiness & Leadership Skills" },
  ],
  "CS-AI|7": [
    { code: "", name: "Big Data & Analytics" },
    { code: "", name: "Information Security" },
    { code: "", name: "Professional Elective-4" },
    { code: "", name: "Professional Elective-5" },
    { code: "", name: "Senior Design Project" },
  ],
  "CS-AI|8": [
    { code: "", name: "Professional Elective-6" },
    { code: "", name: "Open Elective" },
    { code: "", name: "Capstone Project 20ECSW402 / Industry Project" },
    { code: "", name: "Industry Training" },
  ],
  "EEE|1": [
    { code: "", name: "Single Variable Calculus" },
    { code: "", name: "Engineering Physics" },
    { code: "", name: "Engineering Mechanics" },
    { code: "", name: "C Programming for Problem Solving" },
    { code: "", name: "Basic Electrical Engineering" },
    { code: "", name: "Social Innovation" },
    { code: "", name: "Engineering Physics Lab" },
  ],
  "EEE|2": [
    { code: "", name: "Multivariable Calculus" },
    { code: "", name: "Engineering Chemistry" },
    { code: "", name: "Problem Solving with Data Structures" },
    { code: "", name: "Engineering Exploration" },
    { code: "", name: "Basic Electronics" },
    { code: "", name: "Basic Mechanical Engg." },
    { code: "", name: "Professional Communication" },
  ],
  "EEE|3": [
    { code: "", name: "Integral Transforms and Statistics" },
    { code: "", name: "Corporate Communication" },
    { code: "", name: "Circuit Analysis" },
    { code: "", name: "Analog Electronic Circuits" },
    {
      code: "",
      name: "Electrical Power Generation, Transmission & Distribution",
    },
    { code: "", name: "Digital Circuits" },
    { code: "", name: "Analog Electronics Laboratory" },
    { code: "", name: "Digital Circuits Laboratory" },
    { code: "", name: "Microcontroller Architecture & Programming" },
  ],
  "EEE|4": [
    { code: "", name: "Linear Algebra and Partial Differential equations" },
    { code: "", name: "Problem Solving Analysis" },
    { code: "", name: "ARM Processor & Applications" },
    { code: "", name: "Linear Control Systems" },
    { code: "", name: "Electrical Machines" },
    { code: "", name: "Signals & Systems" },
    { code: "", name: "Power Electronics" },
    { code: "", name: "ARM Microcontroller Lab" },
    { code: "", name: "Digital System Design using Verilog" },
    { code: "", name: "Data Structure Applications Lab" },
    { code: "", name: "Data Structure Using C Lab (Diploma)" },
  ],
  "EEE|5": [
    { code: "", name: "Arithmetical Thinking & Analytical Reasoning" },
    { code: "", name: "Power System Analysis & Stability" },
    { code: "", name: "OS & Embedded Systems" },
    { code: "", name: "Linear Integrated Circuits" },
    { code: "", name: "Machine Learning" },
    { code: "", name: "Digital Signal Processing" },
    { code: "", name: "Electric Drives & Control" },
    { code: "", name: "RTOS Lab" },
    { code: "", name: "Machines Lab" },
    { code: "", name: "Data acquisition and controls Lab" },
    { code: "", name: "Data Structure Applications Lab" },
    { code: "", name: "Mini project" },
  ],
  "EEE|6": [
    { code: "", name: "Professional Aptitude and Logical reasoning" },
    { code: "", name: "Industry Readiness & Leadership Skills" },
    { code: "", name: "Automotive Electronics" },
    { code: "", name: "CMOS VLSI Circuits" },
    { code: "", name: "Program Elective 1" },
    { code: "", name: "Object Oriented Programming using C++" },
    { code: "", name: "Program Elective 2" },
    { code: "", name: "Battery Management Systems" },
    {
      code: "",
      name: "Modelling and Analysis of Hybrid Electrical Energy Systems",
    },
    { code: "", name: "Power Electronics & Drives lab" },
    { code: "", name: "Automotive Electronics Lab" },
    { code: "", name: "CMOS VLSI Lab" },
    { code: "", name: "Minor Project" },
    { code: "", name: "Data Structure Using C Lab (Diploma)" },
  ],
  "EEE|7": [
    { code: "", name: "Power System Operation & Control" },
    { code: "", name: "Program Elective 3" },
    { code: "", name: "Program Elective 4" },
    { code: "", name: "Program Elective 5" },
    { code: "", name: "Project" },
    { code: "", name: "HSC 4 (CIPE/EVS)" },
    { code: "", name: "Relay and High Voltage Engineering lab" },
  ],
  "EEE|8": [
    { code: "", name: "Program Elective 6" },
    { code: "", name: "Industry Internship" },
    { code: "", name: "Open Elective" },
    { code: "", name: "Project" },
  ],
  "Biomedical|1": [
    { code: "", name: "Single Variable Calculus" },
    { code: "", name: "Engineering Physics" },
    { code: "", name: "Engineering Mechanics" },
    { code: "", name: "C Programming for Problem solving" },
    { code: "", name: "Basic Electrical Engineering" },
    { code: "", name: "Social Innovation" },
    { code: "", name: "Engineering Physics Lab" },
  ],
  "Biomedical|2": [
    { code: "", name: "Multivariable Calculus" },
    { code: "", name: "Engineering Chemistry" },
    { code: "", name: "Problem Solving with Data Structruture" },
    { code: "", name: "Engineering Exploration" },
    { code: "", name: "Basic Electronics" },
    { code: "", name: "Basic Mechanical Engg." },
    { code: "", name: "Professional Communication" },
  ],
  "Biomedical|3": [
    { code: "", name: "Integral Transforms and Statistics" },
    { code: "", name: "Circuit Analysis" },
    { code: "", name: "Analog Electronic Circuits" },
    { code: "", name: "Digital Circuits" },
    { code: "", name: "Electronic Instrumentation and" },
    { code: "", name: "Measurements" },
    { code: "", name: "Digital Circuits Lab" },
    { code: "", name: "Analog Electronic Circuits Lab" },
    { code: "", name: "Microcontroller Architecture & Programming" },
    { code: "", name: "C Programming (Dip)" },
    { code: "", name: "Corporate Communication" },
    { code: "", name: "Calculus and Integral Transforms (Dip)" },
    { code: "", name: "PSE Elective 6" },
    { code: "", name: "Open Elective 1" },
    { code: "", name: "Capstone Project Work" },
  ],
  "Biomedical|4": [
    { code: "", name: "Linear Algebra &Partial Differential" },
    { code: "", name: "Equations" },
    { code: "", name: "Signal Conditioning and Data acquisition" },
    { code: "", name: "Biomedical Instrumentation" },
    { code: "", name: "Human Anatomy and Physiology" },
    { code: "", name: "ARM Processor & Applications" },
    { code: "", name: "ARM Microcontroller Lab" },
    { code: "", name: "Biomedical Instrumentation Lab" },
    { code: "", name: "Signal Conditioning and Data acquisition Lab" },
    { code: "", name: "Data Structure Using C Lab(Diploma)" },
    { code: "", name: "Vector Calculus Differential Equations(Diploma)" },
    { code: "", name: "Problem Solving & Analysis" },
  ],
  "Biomedical|5": [
    { code: "", name: "Fundamentals of Signals and DSP" },
    { code: "", name: "Clinical Instrumentation" },
    { code: "", name: "Therapeutic Devices" },
    { code: "", name: "Operating System and Embedded Systems Design" },
    { code: "", name: "Mini Project" },
    { code: "", name: "Clinical Instrumentation Lab." },
    { code: "", name: "Real Time Operating Systems Lab" },
    { code: "", name: "Arithmetical Thinking and Analytical Reasoning" },
  ],
  "Biomedical|6": [
    { code: "", name: "Biomedical DSP" },
    { code: "", name: "Medical Image Processing" },
    { code: "", name: "Professional Elective-Ol" },
    { code: "", name: "Professional Elective-02" },
    { code: "", name: "Biomedical DSP Lab" },
    { code: "", name: "Medical Image Processing Lab" },
    { code: "", name: "Machine Learning" },
    { code: "", name: "Minor Project" },
    { code: "", name: "Industry Readiness and Leadership Skills" },
  ],
  "Biomedical|7": [
    { code: "", name: "PCl 7: Medical Imaging Systems" },
    { code: "", name: "PSE Elective 3" },
    { code: "", name: "PSE Elective 4" },
    { code: "", name: "PSE Elective 5" },
    { code: "", name: "P3: Senior Design Project" },
    { code: "", name: "CIPE" },
  ],
  "Biomedical|8": [
    { code: "", name: "PSE Elective 6" },
    { code: "", name: "Open Elective 1" },
    { code: "", name: "Capstone Project Work" },
  ],
  "Chemical|1": [
    { code: "", name: "Humanities and Social Sciences" },
    { code: "", name: "Basic Sciences (Physics, Chemistry," },
    { code: "", name: "Mathematics)" },
    { code: "", name: "Engineering Sciences" },
    { code: "", name: "Professional Core Courses + SS" },
    { code: "", name: "Professional Elective Courses" },
    { code: "", name: "Open Electives" },
    { code: "", name: "Mini/ Minor project" },
  ],
  "Chemical|2": [
    { code: "", name: "Humanities and Social Sciences" },
    { code: "", name: "Basic Sciences (Physics, Chemistry," },
    { code: "", name: "Mathematics)" },
    { code: "", name: "Engineering Sciences" },
    { code: "", name: "Professional Core Courses + SS" },
    { code: "", name: "Professional Elective Courses" },
    { code: "", name: "Open Electives" },
    { code: "", name: "Mini/ Minor project" },
  ],
  "Chemical|3": [
    { code: "", name: "Statistics & Integral Transforms" },
    { code: "", name: "Momentum Transfer" },
    { code: "", name: "Particulate Technology" },
    { code: "", name: "Material & Energy Balance Calculations" },
    { code: "", name: "Chemical Process Industries" },
    { code: "", name: "Momentum Transfer Lab" },
    { code: "", name: "Particulate Technology Lab" },
    { code: "", name: "Computer-Aided Drawing Lab." },
    { code: "", name: "Corporate Communication" },
  ],
  "Chemical|4": [
    { code: "", name: "Numerical methods, Linear Algebra and" },
    { code: "", name: "Partial differential equations" },
    { code: "", name: "Industrial Pollution Control" },
    { code: "", name: "Process Heat Transfer" },
    { code: "", name: "Chemical Engineering Thermodynamics" },
    { code: "", name: "Material Science & Engineering" },
    { code: "", name: "Computer-based Chemical Calculations" },
    { code: "", name: "Process Heat Transfer Lab." },
    { code: "", name: "Technical Chemistry Lab." },
    { code: "", name: "Problem Solving & Analysis" },
  ],
  "Chemical|5": [
    { code: "", name: "Process Engineering Economics & Plant" },
    { code: "", name: "Design" },
    { code: "", name: "Computer Applications, Modelling &" },
    { code: "", name: "Simulation" },
    { code: "", name: "Bioprocess Engineering" },
    { code: "", name: "Mass Transfer - I" },
    { code: "", name: "Chemical Reaction Engineering -" },
    { code: "", name: "Mini Project" },
    { code: "", name: "Computer Applications & Simulation Lab." },
    { code: "", name: "Pollution Control Lab." },
    { code: "", name: "Arithmetical Thinking & Analytical Reasoning" },
  ],
  "Chemical|6": [
    { code: "", name: "Chemical Reaction Engineering - II" },
    { code: "", name: "Mass Transfer - II" },
    { code: "", name: "Program Elective - 01" },
    { code: "", name: "Program Elective - 02" },
    { code: "", name: "Professional Aptitude & Logical Reasoning" },
    { code: "", name: "Minor Project" },
    { code: "", name: "Chemical Reaction Engineering Lab" },
    { code: "", name: "Mass Transfer Lab" },
    { code: "", name: "Industry Readiness and Leadership Skills" },
  ],
  "Chemical|7": [
    { code: "", name: "Process Equipment Design & Drawing" },
    { code: "", name: "Process Control & 110T" },
    { code: "", name: "Program Elective - 03" },
    { code: "", name: "Program Elective - 04" },
    { code: "", name: "Program Elective - 05" },
    { code: "", name: "Humanities — 02 (CIPE & EVS)" },
    { code: "", name: "Senior Design Project" },
    { code: "", name: "Process Control Lab" },
  ],
  "Chemical|8": [
    { code: "", name: "Program Elective" },
    { code: "", name: "Open Elective" },
    { code: "", name: "Capstone Project" },
    { code: "", name: "Internship-Training" },
    { code: "", name: "Internship-Project" },
  ],
};

export const BRANCHES = Object.keys(BRANCH_SEMESTERS);

// Helper: get courses for a branch+semester combo
export function getCourses(branch: string, semester: string): Course[] {
  return BRANCH_SEM_COURSES[`${branch}|${semester}`] || [];
}

// Helper: get semesters for a branch
export function getSemesters(branch: string): string[] {
  return BRANCH_SEMESTERS[branch] || [];
}

// Legacy compat — flat subject list per branch (for existing notes)
export const BRANCH_SUBJECTS: Record<string, string[]> = {};
for (const branch of BRANCHES) {
  const allCourses = new Set<string>();
  for (const sem of getSemesters(branch)) {
    for (const c of getCourses(branch, sem)) {
      allCourses.add(c.name);
    }
  }
  BRANCH_SUBJECTS[branch] = Array.from(allCourses);
}

export const SEMESTERS = ["1", "2", "3", "4", "5", "6", "7", "8"];
